language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements_dev.txt
script:
  - nosetests --with-coverage --cover-package=src